FIX: childcare_vs_eldercare.Rmd compilation error - remove nonexistent Household_ID column
The col_select was trying to read 'Household_ID' which doesn't exist in TimeUse106PER.dta.
The household_id is correctly created on line 110 by pasting FSU_Serial_No and Sample_HH_No.
This fixes the compilation error: 'Column Household_ID doesn't exist.'